package com.android_batch_31.designdemo;

import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Toast;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.DefaultItemAnimator;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonArrayRequest;

import org.json.JSONArray;
import org.json.JSONException;

import java.util.ArrayList;

import butterknife.BindView;
import butterknife.ButterKnife;
import butterknife.OnClick;
import butterknife.Optional;

public class CartContainer extends AppCompatActivity {

    @BindView(R.id.reccart) RecyclerView reccart;
    ArrayList<Cart> CartList = new ArrayList<>();
    Context ctx=this;
    Storage storage;

    @Optional
    @OnClick (R.id.btnproceedtocheckout) void OnClick(View v)
    {
        Intent SwitchIntent = new Intent (ctx,Checkout.class);
        startActivity(SwitchIntent);
    }


    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_cart_container);
        ButterKnife.bind(this);
        storage = new Storage(ctx);
        SendRequest();
    }

    private void SendRequest() {
        String WebServiceUrl = Common.getWebServiceUrl() + "cart.php?customerid="
                + storage.read("id",Storage.INTEGER).toString();   //here id(customerid) in storage class is id generated by the system at the time of login.It is stored in customer table under id column in database.
        JsonArrayRequest request = new JsonArrayRequest(WebServiceUrl, new Response.Listener<JSONArray>() {
            @Override	//  we used JsonArrayRequest class so don't need getParams() method.
            public void onResponse(JSONArray response) {
                // [{"error":"no error"},
                // {"count":2},
                // {"id":"3","title":"iphone 11","price":"99000","photo":"iphone.jpg","quantity":"2"},
                // {"id":"4","title":"Nexus one","price":"21000","photo":"nexus.jpg","quantity":"1"}]
                log.d(response.toString());
                try
                {
                    String error = response.getJSONObject(0).getString("error");
                    if(error.equals("no error")==false)
                    {
                        Toast.makeText(ctx,error,Toast.LENGTH_LONG).show();
                    }
                    else
                    {
                        int count = response.getJSONObject(1).getInt("count");
                        if(count==0)
                            Toast.makeText(ctx,"Cart is empty",Toast.LENGTH_LONG).show();
                        else
                        {
                            String cartid,title,photo,productid;
                            int price, quantity;
                            int size = response.length();
                            for(int i=2;i<size;i++) //2
                            {
                                cartid = response.getJSONObject(i).getString("cartid");
                                productid = response.getJSONObject(i).getString("productid");
                                title = response.getJSONObject(i).getString("title");
                                photo = response.getJSONObject(i).getString("photo");
                                //we have to get price & quantity as String in response as below bcoz Json output of webservice for both these
                                // vaiables is in " "(double quote). But we have to do arithmatic operation of both these variables in CartAdapter.java,
                                // so we have converted it in integer through wrapper class as below.
                                price = Integer.parseInt(response.getJSONObject(i).getString("price"));
                                quantity = Integer.parseInt(response.getJSONObject(i).getString("quantity"));

                                CartList.add(new Cart(cartid,title,photo,productid,price,quantity));  // from here cartid, title, price, photo, quantity will be get and set in Cart.java. The sequence of variables should be same.
                            }
                            CartAdapter adapter = new CartAdapter(ctx, CartList);
                            reccart.setLayoutManager(new GridLayoutManager(ctx,1));
                            reccart.setItemAnimator(new DefaultItemAnimator());
                            reccart.setAdapter(adapter);
                        }
                    }
                }
                catch (JSONException e) {
                    log.e(e.getMessage(),ctx);
                }
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                AlertDialog.Builder b1 = new AlertDialog.Builder(ctx);
                b1.setTitle("Network error");
                b1.setMessage(Common.getMessage());
                b1.setIcon(R.mipmap.ic_launcher);
                b1.setPositiveButton("retry", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        SendRequest();
                    }
                });

                b1.setNegativeButton("cancel", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        b1.create().dismiss();
                    }
                });
                b1.create().show();
            }
        });
        request.setRetryPolicy(Common.getRetryPolicy());
        AppController.getInstance().addToRequestQueue(request);
    }

}
