package com.android_batch_31.designdemo;

import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.os.Bundle;
import android.widget.Toast;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.DefaultItemAnimator;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonArrayRequest;

import org.json.JSONArray;
import org.json.JSONException;

import java.util.ArrayList;

import butterknife.BindView;
import butterknife.ButterKnife;

public class MyWishListContainer extends AppCompatActivity {

    @BindView(R.id.recwishlist) RecyclerView recwishlist;
    ArrayList<WishList> MyWishList = new ArrayList<>();
    Context ctx=this;
    Storage storage;
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.wishlist_container);
        ButterKnife.bind(this);
        storage = new Storage(ctx);
        SendRequest();
    }

    private void SendRequest() {
        String WebServiceUrl = Common.getWebServiceUrl() + "wishlist.php?customerid="
                + storage.read("id",Storage.INTEGER).toString();   //here id(customerid) in storage class is id generated by the system at the time of login.It is stored in customer table under id column in database.
        JsonArrayRequest request = new JsonArrayRequest(WebServiceUrl, new Response.Listener<JSONArray>() {
            @Override	//  we used JsonArrayRequest class so don't need getParams() method.
            public void onResponse(JSONArray response) {
                // [{"error":"no error"},
                // {"count":2},
                // {"id":"4","title":"Nexus one","price":"21000","photo":"nexus.jpg"},
                // {"id":"3","title":"iphone 11","price":"99000","photo":"iphone.jpg"}]
                log.d(response.toString());
                try
                {
                    String error = response.getJSONObject(0).getString("error");
                    if(error.equals("no error")==false)
                    {
                        Toast.makeText(ctx,error,Toast.LENGTH_LONG).show();
                    }
                    else
                    {
                        int count = response.getJSONObject(1).getInt("count");
                        if(count==0)
                            Toast.makeText(ctx,"wishlist is empty",Toast.LENGTH_LONG).show();
                        else
                        {
                            String id,title,photo,price;
                            int size = response.length();
                            for(int i=2;i<size;i++) //2
                            {
                                id = response.getJSONObject(i).getString("id");
                                title = response.getJSONObject(i).getString("title");
                                price = response.getJSONObject(i).getString("price");
                                photo = response.getJSONObject(i).getString("photo");
                                MyWishList.add(new WishList(id,title,photo,price)); // from here id, title, price, photo will be get and set in WishList.java
                            }
                            WishListAdapter adapter = new WishListAdapter(ctx,MyWishList);
                            recwishlist.setLayoutManager(new GridLayoutManager(ctx,2));
                            recwishlist.setItemAnimator(new DefaultItemAnimator());
                            recwishlist.setAdapter(adapter);
                        }
                    }
                }
                catch (JSONException e) {
                    log.e(e.getMessage(),ctx);
                }
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                AlertDialog.Builder b1 = new AlertDialog.Builder(ctx);
                b1.setTitle("Network error");
                b1.setMessage(Common.getMessage());
                b1.setIcon(R.mipmap.ic_launcher);
                b1.setPositiveButton("retry", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        SendRequest();
                    }
                });

                b1.setNegativeButton("cancel", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        b1.create().dismiss();
                    }
                });
                b1.create().show();
            }
        });
        request.setRetryPolicy(Common.getRetryPolicy());
        AppController.getInstance().addToRequestQueue(request);
    }
}
